name: screenshot_callback_example
description: Demonstrates how to use the screenshot_callback plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: "2.2.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  screenshot_callback_fork:
    path: ../

flutter:
  uses-material-design: true